version: "3.9"  # optional since v1.27.0
services:
  my-container:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - ./:/ReactApp:ro
      - /ReactApp/node_modules
    tmpfs:
      - /ReactApp/node_modules